--LOADING CLEAN DATA INTO silver.erp_LOC_A101

INSERT INTO silver.erp_LOC_A101
(
CID,
CNTRY )
SELECT
REPLACE (CID,'-' , '')CID,
CASE WHEN UPPER (TRIM(CNTRY))='DE' THEN 'GERMANY'
	 WHEN UPPER (TRIM(CNTRY)) = 'US' OR CNTRY = 'USA' THEN 'UNITED STATES'
	 WHEN UPPER (TRIM(CNTRY)) = ' ' OR CNTRY IS NULL THEN 'NOT AVILABLE'
	 ELSE UPPER(TRIM(CNTRY))
END AS CNTRY
FROM bronze.erp_LOC_A101;
