--LOADING CLEANED DATA INTO SILVER.erp_CUST_AZ12
INSERT INTO SILVER.erp_CUST_AZ12(
CID,
BDATE,
GEN
)
SELECT  
CASE WHEN CID LIKE 'NAS%' THEN SUBSTRING( CID,4,LEN(CID))
	 ELSE CID 
	END AS CID,
CASE WHEN  BDATE> GETDATE() THEN NULL
	ELSE BDATE
END AS BDATE,
CASE WHEN UPPER (TRIM (GEN)) IN ('M' , 'Male') THEN 'MALE'
	 WHEN UPPER (TRIM (GEN)) IN('F' , 'Female') THEN 'FEMALE'
	 ELSE 'NOT AVILABLE'
END AS GEN
FROM bronze.erp_CUST_AZ12;

SELECT GEN, COUNT(*) FROM SILVER.erp_CUST_AZ12
GROUP BY GEN
