SELECT * FROM bronze.erp_LOC_A101;
SELECT * FROM silver.crm_cust_info;

-- DATA ISSUE-1
-- REPLACING - TO FIND COMMON VALUES IN cst_key in silver.crm_cust_info

SELECT 
REPLACE (CID,'-' , '')CID
FROM bronze.erp_LOC_A101
WHERE REPLACE (CID,'-' , '') NOT IN (SELECT cst_key FROM silver.crm_cust_info);

--RESULT : CLEANED AND ALL DATA IS PRESENT IN silver.crm_cust_info

-- DATA ISSUE-2
-- FIXING CONSISTENCY AND LOW CARDINALITY

SELECT DISTINCT CNTRY FROM bronze.erp_LOC_A101;

-- REPLACING ABBREVIATION 

SELECT DISTINCT CNTRY,
CASE WHEN UPPER (TRIM(CNTRY))='DE' THEN 'GERMANY'
	 WHEN UPPER (TRIM(CNTRY)) = 'US' OR CNTRY = 'USA' THEN 'UNITED STATES'
	 WHEN UPPER (TRIM(CNTRY)) = ' ' OR CNTRY IS NULL THEN 'NOT AVILABLE'
	 ELSE UPPER(TRIM(CNTRY))
END AS CNTRY
FROM bronze.erp_LOC_A101
ORDER BY CNTRY;


-- RESULT: DATA CLEANED