
--DATA QUALITY CHECK -1
--DATA CONSISTENCY AND REMOVING UNWANTED SPACE


SELECT * FROM bronze.erp_PX_CAT_G1V2;

SELECT DISTINCT ID FROM bronze.erp_PX_CAT_G1V2
WHERE TRIM (ID) !=ID; 

--RECORDS: NO RECORDS
--CLEANED DATA
SELECT DISTINCT CAT FROM bronze.erp_PX_CAT_G1V2
SELECT CAT FROM bronze.erp_PX_CAT_G1V2
WHERE TRIM (CAT) !=CAT; 
--RECORDS: NO RECORDS
--CLEANED DATA

SELECT DISTINCT SUBCAT FROM bronze.erp_PX_CAT_G1V2
SELECT SUBCAT FROM bronze.erp_PX_CAT_G1V2
WHERE TRIM (SUBCAT) != SUBCAT; 
--RECORDS: NO RECORDS
--CLEANED DATA

SELECT DISTINCT MAINTENANCE FROM bronze.erp_PX_CAT_G1V2

--RECORDS: NO RECORDS
--CLEANED DATA

SELECT * FROM bronze.erp_PX_CAT_G1V2
WHERE ID  NOT IN (SELECT cat_id FROM SILVER.crm_prd_info);

--RESULT : 1 RECORD FOUND 